defmodule Mix.Tasks.ExoReport do
  @shortdoc "Launches the Allure dashboard for exo-bdd test results"

  @moduledoc """
  Launches the Allure dashboard with live-reloading, watching for new test
  results as they are generated by `mix exo_test`.

  All exo-bdd test runs write Allure results to `tools/exo-bdd/allure-results/`
  regardless of which app config is used, so this single dashboard shows
  collated results from all apps.

  ## Usage

      # Launch the dashboard (watches for new results)
      mix exo_report

      # Use a custom results directory
      mix exo_report --results-dir custom-dir

  ## Options

    * `--results-dir` - Path to the Allure results directory, relative to `tools/exo-bdd/`.
      Defaults to `allure-results`.

  ## Workflow

  1. Run tests with Allure enabled: `mix exo_test` (with `report.allure: true` in config)
  2. Launch the dashboard: `mix exo_report`
  3. Re-run tests in another terminal -- the dashboard auto-refreshes
  """

  use Mix.Task
  use Boundary, top_level?: true

  @switches [results_dir: :string]

  @impl Mix.Task
  def run(args) do
    {opts, _rest, _} = OptionParser.parse(args, switches: @switches)

    if bun_available?() do
      do_run(opts)
    else
      Mix.shell().info([
        :yellow,
        "Skipping exo-bdd report: bun is not installed. ",
        "Install bun (https://bun.sh) to use the Allure dashboard.\n"
      ])

      :ok
    end
  end

  defp do_run(opts) do
    umbrella_root = umbrella_root()
    exo_bdd_root = Path.join(umbrella_root, "tools/exo-bdd")
    results_dir = Keyword.get(opts, :results_dir)

    cmd_args = build_cmd_args(results_dir)

    Mix.shell().info([:cyan, "Launching Allure dashboard...\n"])
    run_bun(cmd_args, exo_bdd_root)
  end

  @doc false
  def build_cmd_args(results_dir \\ nil) do
    base = ["run", "src/cli/index.ts", "serve"]

    case results_dir do
      nil -> base
      dir -> base ++ ["--results-dir", dir]
    end
  end

  defp run_bun(cmd_args, exo_bdd_root) do
    case System.cmd("bun", cmd_args, cd: exo_bdd_root, into: IO.stream(:stdio, :line)) do
      {_, 0} ->
        :ok

      {_, code} ->
        Mix.raise("Allure dashboard exited with code #{code}")
    end
  rescue
    e in ErlangError ->
      handle_erlang_error(e, __STACKTRACE__)
  end

  defp handle_erlang_error(%ErlangError{original: :enoent}, _stacktrace) do
    Mix.raise(
      "bun is not installed or not in PATH. Install it with: curl -fsSL https://bun.sh/install | bash"
    )
  end

  defp handle_erlang_error(e, stacktrace) do
    reraise e, stacktrace
  end

  defp bun_available? do
    System.find_executable("bun") != nil
  end

  defp umbrella_root do
    case Mix.Project.config()[:build_path] do
      nil ->
        File.cwd!()

      build_path ->
        build_path
        |> Path.expand()
        |> Path.dirname()
    end
  end
end
